# Generated by Django 6.0.4 on 2026-05-11 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_alter_client_id'),
        ('company_app', '0002_alter_company_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='responsible_user_id',
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='company_app.company'),
        ),
        migrations.AddField(
            model_name='client',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
