# Generated by Django 6.0.4 on 2026-05-05 18:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre completo de la empresa.', max_length=150)),
                ('cuil', models.CharField(help_text='Número de CUIL.', max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Teléfono de contacto.', max_length=20, null=True)),
                ('email', models.EmailField(help_text='Correo electrónico único.', max_length=254, unique=True)),
                ('enabled', models.BooleanField(default=True, help_text='Indica si la empresa está activa en el sistema.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
