# Generated by Django 6.0.4 on 2026-05-10 23:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Título breve de la tarea.', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Descripción detallada de la tarea.', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Fecha límite de la tarea.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('cancelled', 'Cancelada'), ('done', 'Completada')], default='pending', help_text='Estado actual de la tarea.', max_length=15)),
                ('enabled', models.BooleanField(default=True, help_text='Indica si la tarea está activa en el sistema.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(help_text='Usuario asignado a la tarea.', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(help_text='Cliente asociado a la tarea.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='client_app.client')),
            ],
        ),
    ]
